name: compliance-tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  compliance-tests:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
    - uses: actions/checkout@v1
    - name: StandardRB Linter
      uses: standardrb/standard-ruby-action@v0.0.5
      with:
        autofix: false
